# https://docs.drone.io/pipeline/environment/reference/

kind: pipeline
name: test appium/appium
type: docker

steps:
- name: test
  image: appium/appium
  commands:
  - echo hello
  - echo world
  - echo $DRONE_BRANCH
