
kind: pipeline
type: docker
name: default

steps:
- name: greeting
  image: alpine
  commands:
  - echo hello
  - echo world
# https://docs.drone.io/pipeline/docker/syntax/trigger/

kind: pipeline
name: arm

platform:
  os: linux
  arch: arm

steps:

- name: build
  image: ubuntu
  commands:
    - echo 'hello arm'

- name: build1
  image: ubuntu
  commands:
    - echo 'hello arm'
