
kind: pipeline
type: docker
name: hello_failure

steps:
- name: greeting
  failure: ignore
  image: alpine
  commands:
  - ./hello_failure/fail.sh
---

kind: pipeline
type: docker
name: helloworld

steps:
- name: greeting
  image: alpine
  commands:
  - echo hello
  - echo world
