# https://docs.drone.io/pipeline/environment/reference/

kind: pipeline
name: helloworld
type: docker

steps:
- name: helloworld
  image: ubuntu:18.04
  environment:
    DOCKERHUB_USER:
      from_secret: dockerhub_user
    DOCKERHUB_PASSWORD:
      from_secret: dockerhub_password
  volumes:
  - name: docker_socket
    path: /var/run/docker.sock
  commands:
  - apt-get update
  - apt-get install -yq software-properties-common
  - apt-get install -yq lsb-release
  - cd hello-docker-build
  -   apt-get remove docker docker-engine docker.io
  -   apt-get install -yq apt-transport-https ca-certificates curl software-properties-common
  -   curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -
  -   add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu  $(lsb_release -cs)  stable"
  -   apt-get install -yq docker-ce
  -   docker build -t logickee/ubuntu-docker .
  -   docker login -u $DOCKERHUB_USER -p $DOCKERHUB_PASSWORD
  -   docker push logickee/ubuntu-docker
  - cd ..



volumes:
- name: docker_socket
  host:
    path: /var/run/docker.sock


---
kind: secret
name: dockerhub_user
data: ot4LjMJdZkjghfrqYIgt1oiO3PnRYlTaJG+0TkP+zg1GHI9a


---
kind: secret
name: dockerhub_password
data: wsiguwAjyBgzJo7CUC0xPxTFxkW6TWliFsL0RKI0zDPTabwnAsw=
