# https://docs.drone.io/pipeline/environment/reference/

kind: pipeline
name: helloworld
type: docker

steps:
- name: helloworld
  image: alpine
  volumes:
  - name: cache
    path: /tmp/cache
  commands:
  - ls -l /tmp/cache

volumes:
- name: cache
  host:
    path: /home/logic
