---
kind: pipeline
type: docker
name: backend1

steps:
- name: build
  image: golang
  commands:
  - go build
  - go test

---
kind: pipeline
type: docker
name: frontend1

steps:
- name: build
  image: node
  commands:
  - npm install
  - npm test