
kind: pipeline
type: docker
# name: hello_failure

steps:
- name: greeting
  image: alpine
  commands:
  - echo hello
  - echo world

---

kind: pipeline
type: docker
name: helloworld

steps:
- name: greeting
  image: alpine
  commands:
  - echo hello
  - echo world
