kind: pipeline
type: docker
name: default

steps:
- name: build
  image: node
  volumes:
  - name: logic_home
    path: /tmp/home
  commands:
  - npm install
  - npm test

volumes:
- name: logic_home
  host:
    path: /home/logic/_workspace