
kind: pipeline
type: docker
name: hello_failure

steps:
- name: hello_failure
  failure: ignore
  image: ubuntu
  commands:
  - ./hello_failure/fail.sh

---

kind: pipeline
type: docker
name: hello-merger

steps:
- name: hello-merger
  image: alpine
  commands:
  - echo hello
  - echo world

---
kind: pipeline
name: arm

platform:
  os: linux
  arch: arm



steps:
- name: build
  image: ubuntu
  environment:
    SLACK_TOKEN:
      from_secret: slack_token

---

kind: secret
name: slack_token
data: UsAb4S8kczyyOKWbdgpd5YnKrq3YuOBHiPyt7/Eiwj6bjvMtqkyxiQEWQDdXwY8=

---

kind: pipeline
type: docker
name: helloworld

steps:
- name: helloworld
  image: alpine
  commands:
  - echo hello
  - echo world
