# https://docs.drone.io/pipeline/environment/reference/

kind: pipeline
name: helloworld
type: docker

steps:
- name: test hello-docker-build-appium
  image: logickee/ubuntu-docker
  volumes:
  - name: docker_socket
    path: /var/run/docker.sock
  commands:
  - docker -v


volumes:
- name: docker_socket
  host:
    path: /var/run/docker.sock