kind: pipeline
type: docker
name: hello-merger

steps:
- name: hello-merger
  image: logickee/ubuntu-basic
  commands:
  - echo $DRONE_BRANCH

  - git clone https://$GITHUB_TOKEN@github.com/louiscklaw/drone-ci-playlist.git /tmp/test_git_dir

  - cd /tmp/test_git_dir
  -   git checkout $DRONE_BRANCH
  - cd -

  - cd hello-merger
  -   pipenv run python3 ./src/main.py /tmp/test_git_dir
  - cd -

  environment:
    GITHUB_TOKEN:
      from_secret: GITHUB_TOKEN
