kind: pipeline
type: docker
name: hello-merger

steps:
- name: hello-merger
  image: logickee/ubuntu-basic
  commands:
  - git clone https://$GITHUB_TOKEN@github.com/louiscklaw/drone-ci-playlist.git /tmp/test_git_dir
  - cd hello-merger
  -   pipenv run python3 ./src/main.py /tmp/test_git_dir

  environment:
    GITHUB_TOKEN:
      from_secret: GITHUB_TOKEN

---
kind: secret
name: GITHUB_TOKEN
data: KahdXW1UO0TePy8Fh5BQ0ghArK0X3JYtDP3aQMCyrt9fX0gYLWv8Qp1p4f4uzXt+mgKWXIQTVuH1RfvX7UwIOxNxWHI=
