kind: pipeline
name: hello-merger
type: docker

steps:
- name: hello-merger
  image: logickee/ubuntu-basic
  commands:
  - echo $DRONE_BRANCH

  - git clone https://$GITHUB_TOKEN@github.com/louiscklaw/drone-ci-playlist.git /tmp/test_git_dir

  - cd /tmp/test_git_dir
  -   git checkout $DRONE_BRANCH
  - cd -

  - cd hello-merger
  -   pipenv run python3 ./src/main.py /tmp/test_git_dir
  - cd -

  environment:
    GITHUB_TOKEN:
      from_secret: GITHUB_TOKEN

# ERROR_CHECK: linter: invalid or unknown pipeline dependency
# depends_on will update by scripts/build.sh
depends_on:
<depends_on>


trigger:
  status:
  - success
  branch:
  - develop
  - test/*


---
kind: secret
name: GITHUB_TOKEN
data: bzDZQ+2HFTzRwXkVM8MmstspQh0rNwkvU+x5IPacewYSIVGe6oewX/4JAJW3i7dJ9T6c4Ea+8zM1NvCc95sbR3qrkH4=
