# https://docs.drone.io/pipeline/environment/reference/

kind: pipeline
type: docker
name: helloworld

steps:
- name: helloworld
  image: node:lts
  commands:
  - echo hello
  - echo world
  - echo $DRONE_BRANCH
  - node -v
  - yarn -v