#
# Ubuntu Dockerfile
#
# https://github.com/dockerfile/ubuntu
#

# Pull base image.
FROM ubuntu:latest

# Install.
RUN apt-get update
RUN apt-get install -y git
RUN apt-get install -y python3 python3-pip
RUN apt-get install -y sudo
RUN apt-get install -y entr rsync
RUN python3 -m pip install pipenv

RUN git config --global user.email "drone_test@louislabs.com" && \
    git config --global user.name "drone_test"

WORKDIR '/root'

# Define default command.
CMD ["bash"]
