#
# Ubuntu Dockerfile
#
# https://github.com/dockerfile/ubuntu
#

# Pull base image.
FROM ubuntu:latest

# Install.
RUN apt-get update
RUN apt-get install -y git
RUN apt-get install -y python3 python3-pip

RUN python3 -m pip install pipenv

# Define default command.
CMD ["bash"]
