# https://docs.drone.io/pipeline/environment/reference/

kind: pipeline
name: helloworld
type: docker

steps:
- name: test hugo-helloworld
  image: ubuntu:18.04
  commands:
  - cd hello-hugo
  -   dpkg -i ./hugo_extended_0.74.3_Linux-64bit.deb
  -
  -   cd hugo-helloworld
  -     hugo -D
  -   cd ..
  - cd ..
