
kind: pipeline
name: hello-secrets

steps:
- name: build
  image: ubuntu
  environment:
    HELLO:
      from_secret: hello

  commands:
  - echo $HELLO

---
kind: secret
name: hello
data: fRBBQR1N0FejBRMwbnYCrzDDqKQLvYLcPmKmXSxoUIcv

---
kind: secret
name: GITHUB_TOKEN
data: KahdXW1UO0TePy8Fh5BQ0ghArK0X3JYtDP3aQMCyrt9fX0gYLWv8Qp1p4f4uzXt+mgKWXIQTVuH1RfvX7UwIOxNxWHI=
