
kind: pipeline
name: hello-secrets

platform:
  os: linux
  arch: arm

steps:
- name: build
  image: ubuntu
  environment:
    SLACK_TOKEN:
      from_secret: slack_token

  commands:
  - echo hello
  - echo world


---
kind: secret
name: slack_token
data: UsAb4S8kczyyOKWbdgpd5YnKrq3YuOBHiPyt7/Eiwj6bjvMtqkyxiQEWQDdXwY8=
