# https://docs.drone.io/pipeline/environment/reference/

kind: pipeline
name: helloworld
type: docker

steps:
- name: helloworld
  image: ubuntu:latest
  commands:
  - echo hello
  - echo world
  - echo $DRONE_BRANCH
  - apt-get update
  - apt-get install -y git
  - apt-get install -y python3 python3-pip
  - apt-get install -y entr rsync
  - python3 -m pip install pipenv
  - pipenv sync
  - pipenv run python3 main.py