kind: pipeline
name: test logickee-raspberry-appium
type: docker

platform:
  os: linux
  arch: arm

steps:
- name: test
  image: logickee/raspberry-appium
  commands:
  - echo hello
  - echo world
  - echo $DRONE_BRANCH
