#!/usr/bin/env bash

docker network create your-network0
docker network create your-network1
docker network create your-network2
docker network create your-network3
docker network create your-network4
docker network create your-network5
docker network create your-network6
docker network create your-network7
docker network create your-network8
docker network create your-network9
docker network create your-network10
docker network create your-network11
docker network create your-network12
docker network create your-network13
docker network create your-network14
docker network create your-network15
docker network create your-network16
docker network create your-network17
docker network create your-network18
docker network create your-network19
docker network create your-network20
docker network create your-network21
docker network create your-network22
docker network create your-network23
docker network create your-network24
docker network create your-network25
docker network create your-network26
docker network create your-network27
docker network create your-network28
docker network create your-network29
docker network create your-network30
docker network create your-network31
docker network create your-network32
docker network create your-network33
docker network create your-network34
docker network create your-network35
docker network create your-network36
docker network create your-network37
docker network create your-network38
docker network create your-network39
docker network create your-network40
docker network create your-network41
docker network create your-network42
docker network create your-network43
docker network create your-network44
docker network create your-network45
docker network create your-network46
docker network create your-network47
docker network create your-network48
docker network create your-network49
docker network create your-network50
docker network create your-network51
docker network create your-network52
docker network create your-network53
docker network create your-network54
docker network create your-network55
docker network create your-network56
docker network create your-network57
docker network create your-network58
docker network create your-network59
