#!/usr/bin/env bash

docker network rm your-network0 &
docker network rm your-network1 &
docker network rm your-network2 &
docker network rm your-network3 &
docker network rm your-network4 &
docker network rm your-network5 &
docker network rm your-network6 &
docker network rm your-network7 &
docker network rm your-network8 &
docker network rm your-network9 &
docker network rm your-network10 &
docker network rm your-network11 &
docker network rm your-network12 &
docker network rm your-network13 &
docker network rm your-network14 &
docker network rm your-network15 &
docker network rm your-network16 &
docker network rm your-network17 &
docker network rm your-network18 &
docker network rm your-network19 &
docker network rm your-network20 &
docker network rm your-network21 &
docker network rm your-network22 &
docker network rm your-network23 &
docker network rm your-network24 &
docker network rm your-network25 &
docker network rm your-network26 &
docker network rm your-network27 &
docker network rm your-network28 &
docker network rm your-network29 &
docker network rm your-network30 &
docker network rm your-network31 &
docker network rm your-network32 &
docker network rm your-network33 &
docker network rm your-network34 &
docker network rm your-network35 &
docker network rm your-network36 &
docker network rm your-network37 &
docker network rm your-network38 &
docker network rm your-network39 &
docker network rm your-network40 &
docker network rm your-network41 &
docker network rm your-network42 &
docker network rm your-network43 &
docker network rm your-network44 &
docker network rm your-network45 &
docker network rm your-network46 &
docker network rm your-network47 &
docker network rm your-network48 &
docker network rm your-network49 &
docker network rm your-network50 &
docker network rm your-network51 &
docker network rm your-network52 &
docker network rm your-network53 &
docker network rm your-network54 &
docker network rm your-network55 &
docker network rm your-network56 &
docker network rm your-network57 &
docker network rm your-network58 &
docker network rm your-network59 &

wait
