# https://docs.drone.io/pipeline/environment/reference/

kind: pipeline
name: helloworld
type: docker

steps:
- name: helloworld
  image: alpine
  commands:
  - echo hello
  - echo world
  - echo $DRONE_BRANCH

- name: publish
  image: plugins/gh-pages
  settings:
    username:
      from_secret: github_u
    password:
      from_secret: github_p
    pages_directory: hello-gh-pages/public/

---

kind: secret
name: github_u
data: 0+6dJTLwzNI/Ao/rcqQLeDm+1KVusQoksZdZ/WKtwpDOZJ/inkI=

kind: secret
name: github_p
data: vUJejxoMXAulCSm+QrpzNNRGqreHZOIxAXFuSV6IOh4pak0C1JMKOSG0Jiw=
