# https://docs.drone.io/pipeline/environment/reference/

kind: pipeline
name: helloworld
type: docker

steps:
- name: helloworld
  image: node:lts
  environment:
    GH_TOKEN:
      from_secret: gh_token
  commands:
    - git clone http://louiscklaw:$GH_TOKEN@github.com/louiscklaw/drone-ci-playlist /tmp/drone-ci-playlist

    - cd /tmp/drone-ci-playlist
    - git checkout $DRONE_BRANCH
    -   cd hello-gh-pages
    -     npm install gh-pages -g
    -     gh-pages -d public -b gh-pages

---
kind: secret
name: gh_token
data: jsiRimOeYe7wYVsxd2i842cuCKoX7yChzojECHEcbBV5lx8Abx7H5vr0f4UfkB8uB60p6rIbl+KqOj5LCcpY2nLCeDU=
