# https://docs.drone.io/pipeline/environment/reference/

# build this drone require a trusted permission in setting page
# to show the trusted options in setting page require an administrator
# grant admin to a user requires setting options in drone server up command script

kind: pipeline
name: helloworld
type: docker

steps:
- name: helloworld
  image: ubuntu:18.04
  environment:
    DEBIAN_FRONTEND: noninteractive
    DOCKERHUB_USER:
      from_secret: dockerhub_user
    DOCKERHUB_PASSWORD:
      from_secret: dockerhub_password
  volumes:
  - name: docker_socket
    path: /var/run/docker.sock
  commands:
  - apt-get update
  - apt-get install -yq software-properties-common
  - apt-get install -yq lsb-release
  # - apt-get remove docker docker-engine docker.io
  - apt-get install -yq apt-transport-https ca-certificates curl software-properties-common
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -
  - add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu  $(lsb_release -cs)  stable"
  - apt-get install -yq docker-ce

  - cd hello-docker-build
  -   docker build -t logickee/ubuntu-docker .
  - cd ..

  # check if the environment variables can be accessed
  - echo $DOCKERHUB_USER
  - echo $DOCKERHUB_PASSWORD

  - docker login -u $DOCKERHUB_USER -p $DOCKERHUB_PASSWORD
  - docker push logickee/ubuntu-docker



volumes:
- name: docker_socket
  host:
    path: /var/run/docker.sock


---
kind: secret
name: dockerhub_user
data: jypUaLjjakqOLk7fIH0hQpVGTITfyp1qCD0FBJpr+cRVqaPa


---
kind: secret
name: dockerhub_password
data: A62QyXrD7jBNcH8QqCk6rA95JOdfLyWwt0e5NuPyk8LmFDUPuoThc1rCag==
