# https://docs.drone.io/pipeline/environment/reference/

# build this drone require a trusted permission in setting page
# to show the trusted options in setting page require an administrator
# grant admin to a user requires setting options in drone server up command script

kind: pipeline
name: helloworld
type: docker

steps:
- name: helloworld
  image: ubuntu:18.04
  volumes:
  - name: docker_socket
    path: /var/run/docker.sock
  commands:
  - apt-get update
  - apt-get install -yq software-properties-common
  - apt-get install -yq lsb-release
  - cd hello-docker-build
  -   apt-get remove docker docker-engine docker.io
  -   apt-get install -yq apt-transport-https ca-certificates curl software-properties-common
  -   curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -
  -   add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu  $(lsb_release -cs)  stable"
  -   apt-get install -yq docker-ce
  -   docker build .
  - cd ..



volumes:
- name: docker_socket
  host:
    path: /var/run/docker.sock