# https://docs.drone.io/pipeline/environment/reference/

kind: pipeline
name: helloworld
type: docker

steps:
- name: helloworld
  image: alpine
  volumes:
  - name: docker_socket
    path: /var/run
  commands:
  - ls -l /var/run/docker.sock



volumes:
- name: docker_socket
  host:
    path: /var/run
