FROM ubuntu:18.04

RUN apt-get update
RUN apt-get install -yq git
RUN apt-get install -yq software-properties-common
RUN apt-get install -yq lsb-release
RUN apt-get remove docker docker-engine docker.io
RUN apt-get install -yq apt-transport-https ca-certificates curl software-properties-common
RUN curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -
RUN add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu  $(lsb_release -cs)  stable"
RUN apt-get install -yq docker-ce

CMD ['bash']
