# https://docs.drone.io/pipeline/environment/reference/

kind: pipeline
name: helloworld
type: docker

steps:
- name: helloworld
  image: alpine
  commands:
  - add-apt-repository -y ppa:freecad-maintainers/freecad-stable
  - apt-get update
  - apt-get install -y freecad freecad-python3
  - mkdir /usr/lib/freecad-python3/Mod

  - for i in $(find . -name '*.FCStd'); do python3 travis-freecad-checking/freecad_open_test.py $i; done
