# https://docs.drone.io/pipeline/environment/reference/

kind: pipeline
name: helloworld
type: docker

steps:
- name: helloworld
  image: alpine
  commands:
  - sudo add-apt-repository -y ppa:freecad-maintainers/freecad-stable
  - sudo apt-get update
  - sudo apt-get install -y freecad freecad-python3
  - sudo mkdir /usr/lib/freecad-python3/Mod