FROM ubuntu:20.04

RUN apt-get update && \
  apt-get install -y --no-install-recommends \
  systemd systemd-sysv dbus dbus-user-session

ENV a=apple11

COPY docker-entrypoint.sh /

ENTRYPOINT ["/docker-entrypoint.sh"]
